# Uncomment the next line to define a global platform for your project
platform :ios, '6.0'

target 'HelloRMCharacter' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for HelloRMCharacter
  pod 'RMCharacter', path: '../..'
  pod 'RMShared', path: '../../../RMShared'
end
