# Uncomment the next line to define a global platform for your project
platform :ios, '6.0'

target 'RMCoreTest' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for HelloRomo
  pod 'RMShared', path: '../../RMShared'
  pod 'RMCore', path: '../../RMCore'
end
