//==============================================================================
//                             _
//                            | | (_)
//   _ __ ___  _ __ ___   ___ | |_ ___   _____
//  | '__/ _ \| '_ ` _ \ / _ \| __| \ \ / / _ \
//  | | | (_) | | | | | | (_) | |_| |\ V /  __/
//  |_|  \___/|_| |_| |_|\___/ \__|_| \_/ \___|
//
//==============================================================================
//
//  RMCoreRobotMotion.h
//  RMCore
//
//  Created by Romotive on 4/29/13.
//  Copyright (c) 2013 Romotive. All rights reserved.
//
//==============================================================================
/** @file RMCoreRobotMotion.h
 @brief Private header for Robot Motion module.  This is the central point for 
 receiving and distrubuting IMU data.  
 
 In addition to collecting IMU data this module is also used to do basic set up 
 and enabling/disabling of the IMU unit (indirectly, through calls to a 
 RMCoreRobot).  It acts as the handler for receiving IMU data and passes that 
 data along to the iDevice and mobility platform modules where it may be
 further processed, as necessary.
 */

#import <Foundation/Foundation.h>
#import "RMCoreMotionInterface.h"
#import "RMCoreDeviceMotion.h"
#import "RMCorePlatformMotion.h"
#import "RobotMotionProtocol.h"

/**
 @brief An RMCoreRobotMotion object conforms to the IMUDataUpdate protocol,
 which makes it responsible for receiving data generated by the IMU module.
 */
@interface RMCoreRobotMotion : NSObject <IMUDataUpdate> 

/**
 Provides access to the Romotive IMU interface that gives access to the IMU unit
 via the CoreMotion framework.
 */
@property (nonatomic, strong) RMCoreMotionInterface *IMU;

/**
 This is the place where IMU data from the iDevice's framework is sent.  Some
 post-processing may occur there.
 */
@property (nonatomic, strong) RMCoreDeviceMotion *iDevice;

/**
 This is the place where IMU data that is represented in the mobility platform's
 reference frame is stored.  It is made of post-processed device IMU data.
 */
@property (nonatomic, strong) RMCorePlatformMotion *platform;

/**
 Set to YES to enable RobotMotion (IMU).
 */
@property (nonatomic, getter=isEnabled) BOOL enabled;

/**
 Indicates if RobotMotion is ready (IMU is sourcing good data)
 */
@property (nonatomic, readonly) BOOL ready;

/**
 Set refresh rate of the RobotMotion module (Hz)
 */
@property (nonatomic) float dataUpdateRate;

@end
