# Uncomment the next line to define a global platform for your project
platform :ios, '6.0.0'

target 'HelloRMVision' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for HelloRMVision
  pod 'RMVision', path: '../..'
  pod 'RMShared', path: '../../../RMShared'
end