# Uncomment the next line to define a global platform for your project
platform :ios, '7.0'

target 'HelloRMCoreSwift' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HelloRMCoreSwift

  # Pods for HelloRMCore
  pod 'Romo', path: '../../..'
  pod 'Romo/RMCore', path: '../../..'
  pod 'CocoaLumberjack'
end
