# Uncomment the next line to define a global platform for your project
platform :ios, '6.0'

target 'Romo X' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Romo X
  pod 'CocoaLumberjack'
  pod 'AFNetworking'
  pod 'Romo', path: '../SDK'
  pod 'Romo/RMCore', path: '../SDK'
  pod 'Romo/RMCharacter', path: '../SDK'
  pod 'Romo/RMVision', path: '../SDK'

end

target 'Romo X Control' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Romo X Control
  pod 'CocoaLumberjack'
  pod 'Romo', path: '../SDK'
end
