# Uncomment the next line to define a global platform for your project
platform :ios, '6.0'

target 'Romo X' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Romo X
  pod 'CocoaLumberjack'
  pod 'AFNetworking'
  pod 'RMCore', path: '../SDK/RMCore'
  pod 'RMVision', path: '../SDK/RMVision'
  pod 'RMCharacter', path: '../SDK/RMCharacter'
  pod 'RMShared', path: '../SDK/RMShared'
end

target 'Romo X Control' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Romo X Control
  pod 'CocoaLumberjack'
  pod 'RMShared', path: '../SDK/RMShared'
end
