# Uncomment the next line to define a global platform for your project
platform :ios, '6.1.6'

target 'HelloRMVision' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for HelloRMVision
  pod 'RMVision', path: '../../RMVision'
  pod 'RMShared', path: '../../RMShared'
end